name: Publish

on:
  push:
    branches:    
      - windows

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and build
        run: |
          yarn install
          yarn postinstall
          yarn build

      - name: Publish releases
        run: |
          yarn electron-builder -- --publish always --windows
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ApiChain_windows
          path: release/build/
