name: Publish

on:
  push:
    branches:    
      - macos

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and build
        run: |
          yarn install
          yarn postinstall
          yarn build

      - name: Merge main into macos branch
        run: |
          git fetch origin macos:macos
          git checkout macos
          git merge main --no-edit
          git push origin macos

      - name: Merge main into windows branch
        run: |
          git fetch origin windows:windows
          git checkout windows
          git merge main --no-edit
          git push origin windows
